### ISSUE TITLE
加载图书后，无法调取图书目录

### ISSUE THREAD

**Issue by AmbroseRen** [ZTFtrue/BookReader#8]
main-es2015.a087988cea49c598bbc0.js格式化后29003行报鼠标监听事件错误.

**Comment by ZTFtrue** [comment]
麻烦提供一下以下信息:

运行平台: Linux, Windows, macOS, Android, IOS, etc.
使用浏览器: Chrome, Firefox, etc.
运行设备: 平板, PC,手机, etc.

可以的话提供一下更详细的错误.

**Comment by AmbroseRen** [comment]
哥，你终于上线了，我刚在看你的源码。就是家里前端环境不全，我没拉下来运行。
笔记本；windowsx64；Chrome；[image: bx1.png]
手机我测过（android），情况是：只能读出来部分，过了两页就卡了，一页还没全部读出来。
我也希望能维护下，看下怎么改

ztftrue ***@***.***> 于2021年3月31日周三 下午8:05写道：

**Comment by AmbroseRen** [comment]
报错图片只能给MD格式……,[截图](https://cdn.jsdelivr.net/gh/AmbroseRen/Picture@master/img/Develop/Error/bx1.png)

**Comment by ZTFtrue** [comment]
现在鼠标点击, 可以显示目录了.
