### ISSUE TITLE
建议功能

### ISSUE THREAD

**Issue by AmbroseRen** [ZTFtrue/BookReader#9]
我又测了一下，兄弟你如果能加一个本地缓存和手机适应就更加好了。我找了刘明野的epub服务项目（他的服务商经常岩机），没找到……我看下有没有能力一起维护哈

**Comment by AmbroseRen** [comment]
老哥，你之前的版本挺好用的。是不是你十天之前改完上传，修个bug出来了，要不回退一个版本测试一下呗

**Comment by ZTFtrue** [comment]
> 老哥，你之前的版本挺好用的。是不是你十天之前改完上传，修个bug出来了，要不回退一个版本测试一下呗

好用是指那个方面? 是没有手机上的bug, 还是鼠标监听事件错误的bug.

前几天改的是键盘事件的处理.

**Comment by AmbroseRen** [comment]
> > 老哥，你之前的版本挺好用的。是不是你十天之前改完上传，修个bug出来了，要不回退一个版本测试一下呗
> 
> 好用是指那个方面? 是没有手机上的bug, 还是鼠标监听事件错误的bug.
> 
> 前几天改的是键盘事件的处理.

之前电脑上面鼠标监听是没有问题的（手机的我不太清楚），改过后加载完图书就弹不出来目录了，我试了一下好像监听鼠标的图层被加载的图书覆盖了，重新刷新有效，但图书没缓存也没了。

**Comment by ZTFtrue** [comment]
> > 老哥，你之前的版本挺好用的。是不是你十天之前改完上传，修个bug出来了，要不回退一个版本测试一下呗
> 
> 好用是指那个方面? 是没有手机上的bug, 还是鼠标监听事件错误的bug.
> 
> 前几天改的是键盘事件的处理.

假日期间我更新一下代码.
另外, 我这里没有测试出鼠标错误信息.

**Comment by ZTFtrue** [comment]
> 不报错误信息，就是加载完图书内容会覆盖鼠标监听，点击不会弹出图书目录。还有个小问题，就是读完上一页到页底，翻到下一页直接也是页低，不是出现在一页最上面。老哥，能改一下最好了。这个轻量化的服务真心好用！比各种公司做的客户端阅读器好太多了，我都为那些公司的阅读器感到羞愧（或许是他们抢占资源故意的吧），反正就是不喜欢笨重的客户端

Press "m" open menu. 

这个功能我忘记说明了,  键盘上按m 就打开了. 要不然复制不方便.

**Comment by AmbroseRen** [comment]
> > 不报错误信息，就是加载完图书内容会覆盖鼠标监听，点击不会弹出图书目录。还有个小问题，就是读完上一页到页底，翻到下一页直接也是页低，不是出现在一页最上面。老哥，能改一下最好了。这个轻量化的服务真心好用！比各种公司做的客户端阅读器好太多了，我都为那些公司的阅读器感到羞愧（或许是他们抢占资源故意的吧），反正就是不喜欢笨重的客户端
> 
> Press "m" open menu.
> 
> 这个功能我忘记说明了, 键盘上按m 就打开了. 要不然复制不方便.

可以用,good。老哥，急需一个书签

**Comment by AmbroseRen** [comment]
老哥，要不改回来吧

**Comment by ZTFtrue** [comment]
增加了右键, 打开菜单的功能.

**Comment by ZTFtrue** [comment]
有很多更改, 点击左右两侧, 也可以翻页. 现在差一个主题
